### ISSUE TITLE
MonoGame vs XNA

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/ModBox#7]
We currently have two projects in the client end, MonoTerraria and Terraria.

To recap, the main benefits with MonoTerraria are:
* Runs in Linux (maybe? Untested?)
* Runs in Mac OS X (maybe? Doesn't work on my Mac)
* Does not require XNA
* Compiles on build server
* More open

The problems with MonoTerraria are:
* Currently, window resizing is expensive/doesn't work correctly. My test to get it working caused FPS to drop to virtually zero by resetting the settings according to what [I found on the subject](http://gamedev.stackexchange.com/questions/68914/issue-with-monogame-resizing).
* Precompiled XNA shaders are a no-go. No vanilla shaders.
* Precompiled XNA music is a no-go, but this is a lot more possible than shader support.

If we get the game working at least on Linux/OS X, we have a major advantage over the normal Terraria client. We could gain a lot of market share just by being a mono client and nothing more, so, free users. As of right now, however, [my issue on OpenTK](https://github.com/opentk/opentk/issues/229) which currently breaks runtime on Mac OS X 10.10.3 hasn't been touched.

My current vote is to drop MonoTerraria in favor of XNA, just for the sake of keeping shaders and precompiled vanilla assets in.

**Comment by nicatronTg** [comment]
@bladecoding @Olink it would be cool if we could come to consensus on this sooner rather than later (before any real client development starts).

**Comment by WhiteXZ** [comment]
You can convert XNA compiled images back to png format. Can you do the same for shaders?

**Comment by nicatronTg** [comment]
@WhiteXZ I'm pretty sure that the precompiled assets cannot be converted, or the general consensus with mono was that losing vanilla shaders was a sacrifice we'd have to make.

**Comment by nicatronTg** [comment]
After some work last night, @Wolfje successfully got ModBox started in Mono under Linux. Note that he didn't have fglrx, so he had no real graphics drivers (expect bugs). As a result, we can conclude that MonoGame can be compiled to work on Linux.

![Linux](http://i.imgur.com/IUkXEqh.png)

**Comment by nicatronTg** [comment]
MonoGame support has been temporarily removed to focus on Windows development. Part of the problem is that calls to user32 are required for user input, and there are other nastier side effects as a result of keeping Mono.

We plan on re-adding Mono support later in the process by supporting it as a build target, rather than as a standalone project. See 6a928d43d3853bcc31971c5d171c8440be696f18.

**Comment by nicatronTg** [comment]
The OpenTK folks replied to my issue finally -- though the problems with user32 still exist.

https://github.com/opentk/opentk/issues/229#issuecomment-82974245
